apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.9/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.3.7/manifests/install.yaml

components:
- github.com/argoproj-labs/argocd-extensions/manifests
