apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          enabled: "yes"
        matchExpressions:
          - {key: cilium-version, operator: Exists}
  template:
    metadata:
      name: '{{name}}-cilium'
    spec:
      project: default
      sources:
      - repoURL: https://helm.cilium.io
        chart: cilium
        targetRevision: '{{metadata.labels.cilium-version}}'
        helm:
          valueFiles:
          - '$values/argocd/apps/cilium/clusters/{{name}}/values.yaml'
      - repoURL: https://github.com/jeffmaas/blah
        targetRevision: HEAD
        ref: values
      destination:
        server: '{{server}}'
        namespace: kube-system
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          name: hubble-ca-cert
          jsonPointers:
          - /data/ca.crt
        - group: ""
          kind: Secret
          name: hubble-ca-secret
          jsonPointers:
          - /data/ca.crt
          - /data/ca.key
        - group: ""
          kind: Secret
          name: cilium-ca
          jsonPointers:
          - /data/ca.crt
          - /data/ca.key
        - group: ""
          kind: Secret
          name: hubble-relay-client-certs
          jsonPointers:
          - /data/ca.crt
          - /data/tls.crt
          - /data/tls.key
        - group: ""
          kind: Secret
          name: hubble-server-certs
          jsonPointers:
          - /data/ca.crt
          - /data/tls.crt
          - /data/tls.key
