apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          enabled: "yes"
          cluster-type: "workload"
  template:
    metadata:
      name: '{{name}}-gateway-api'
    spec:
      destination:
        server: '{{server}}'
      project: default
      source:
        path: argocd/apps/gateway-api
        repoURL: https://github.com/jeffmaas/blah
        targetRevision: HEAD
