apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-bluegreen
  namespace: rollouts-bluegreen
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps/rollouts-bluegreen
    repoURL: https://github.com/jeffmaas/blah
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
