apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollouts-canary
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          enabled: "yes"
          cluster-type: "workload"
  template:
    metadata:
      name: '{{name}}-rollouts-canary'
    spec:
      destination:
        server: '{{server}}'
        namespace: rollouts-canary
      project: default
      source:
        path: argocd/apps/rollouts-canary
        repoURL: https://github.com/jeffmaas/blah
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
