cluster:
  name: "jcm-cluster2"
  id: 2
k8sServiceHost: "192.168.1.52"
k8sServicePort: "6443"
bgpControlPlane:
  enabled: true
bpf:
  masquerade: true
  tproxy: true
ingressController:
  enabled: true
  service:
    insecureNodePort: 30080
    secureNodePort: 30443
    type: "NodePort"
gatewayAPI:
  enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
    - http
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
ipam:
  mode: "kubernetes"
ipv4:
  enabled: true
kubeProxyReplacement: "strict"
loadBalancer:
  algorithm: "maglev"
localRedirectPolicy: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
operator:
  prometheus:
    enabled: true
    port: 9963
    serviceMonitor:
      enabled: true
