apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts
resources:
- https://github.com/argoproj/argo-rollouts/releases/download/v1.6.6/install.yaml
- https://github.com/argoproj/argo-rollouts/releases/download/v1.6.6/notifications-install.yaml
patchesStrategicMerge:
- rollouts-plugin-trafficrouter-gatewayapi.yaml
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: argo-rollouts
  path: rollouts-plugin-trafficrouter-gatewayapi-clusterrole-patch.yaml
