apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts
resources:
- https://github.com/argoproj/argo-rollouts/releases/download/v1.5.1/install.yaml
- https://github.com/argoproj/argo-rollouts/releases/download/v1.5.1/notifications-install.yaml
patchesStrategicMerge:
- rollouts-plugin-trafficrouter-gatewayapi.yaml
