---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: rollouts-canary 
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rollouts-canary
  spec:
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: rollouts-canary
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: rollouts-stable
        port: 80
      - group: ""
        kind: Service
        name: rollouts-canary
        port: 80
      matches:
      - path:
          type: PathPrefix
          value: /
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-stable
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-canary
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-canary-demo
spec:
  replicas: 10
  strategy:
    canary:
      canaryService: rollouts-canary
      stableService: rollouts-stable
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: rollouts-canary
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
